M48
; DRILL file KiCad 10.0.3 date 2026-06-13T19:55:04
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-13T19:55:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X133.54Y-23.5
X133.54Y-81.5
X156.54Y-23.5
X156.54Y-81.5
M30
